name = "MCTSExperiments"
uuid = "dac6b303-fdac-48c1-9f18-7af9a7634e9d"
authors = ["Jason Eckstein <jekyllstein@gmail.com>"]
version = "0.1.0"

[deps]
DecisionMakingProblems = "ea2de46e-05ef-43e3-9855-7b86b16e70ab"
